apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: tomcat1
  template:
    metadata:
      labels: 
        app: tomcat1
    spec:
      nodeName: ip-172-31-43-94
      containers:
      - name: tomcat
        image: tomcat
