apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  replicas: 3
  selector:  
    matchLabels:
      app: tomcat1
  template:
    metadata:
      labels: 
        app: tomcat1
    spec:
      containers:
      - name: tomcat
        image: tomcat
        volumeMounts:
        - name: secretvolume
          mountPath: "/usr/local/tomcat/webapps"
        - name: configvolume
          mountPath: "/usr/local/tomcat/configmap"
      volumes:
      - name: secretvolume
        secret: 
          secretName: secret
      - name: configvolume
        configMap:
          name: democonfigmap 


