apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: tomcat1
  template:
    metadata:
      labels: 
        app: tomcat1
    spec:
      containers:
      - name: tomcat
        image: tomcat
      tolerations:
      - key: "color"
        operator: "Equal"
        value: "red"
        effect: "NoSchedule"
